webproject1920/Controllers/TeamsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using webproject1920.Service.Interfaces;
using webproject1920.ViewModels;

namespace webproject1920.Controllers
{
    public class TeamsController : Controller
    {
        private readonly IMapper _mapper;
        private ITeamsService _teamsService;

        public TeamsController(ITeamsService teamsService, IMapper mapper)
        {
            _mapper = mapper;
            _teamsService = teamsService;
        }

        public async Task<ActionResult> Index()
        {
            var list = await _teamsService.GetAll();

            List<TeamVM> listVM = _mapper.Map<List<TeamVM>>(list);

            return View(listVM);
        }

        public async Task<ActionResult> Detail(int id)
        {
            var team = await _teamsService.GetById(id);
            if (team == null) return NotFound();

            TeamVM teamVM = _mapper.Map<TeamVM>(team);
            return View(teamVM);
        }
    }
}

webproject1920/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Webproject1920</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">    
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("Links", required: false)
</head>
<body class="d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-futbol"></i>
                    webproject1920
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Matches" asp-action="Index">
                                Wedstrijden
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Stadiums" asp-action="Index">
                                Stadions
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Teams" asp-action="Index">
                                Teams
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container wrapper bg-white shadow-lg flex-grow-1">
        <div>
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2020 - webproject1920 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script src="https://kit.fontawesome.com/5482c011d1.js" crossorigin="anonymous"></script>
</body>
</html>