webproject1920/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using webproject1920.Domain.Entities;
using webproject1920.Domain.Interfaces;
using webproject1920.Service;
using webproject1920.Service.Interfaces;
using webproject1920.ViewModels;

namespace webproject1920.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IMatchService _matchService;
        private readonly ITeamsService _teamService;
        private readonly IMatchStadiumLocationService _mslService;
        private readonly IMapper _mapper;

        public MatchesController(IMapper mapper, IMatchService matchService, IMatchStadiumLocationService mslService, ITeamsService teamsService)
        {
            _matchService = matchService;
            _teamService = teamsService;
            _mapper = mapper;
            _mslService = mslService;
        }

        public async Task<ActionResult> Index(MatchCalendarVM vm)
        {
            if (vm.TeamId.HasValue)
            {
                var team = await _teamService.GetById(vm.TeamId.Value);
                if (team == null) return NotFound();
                vm.Team = _mapper.Map<TeamVM>(team);
            }
            return View("Calendar", vm);
        }

        public async Task<ActionResult> Details(int id)
        {
            var match = await _matchService.GetById(id);
            if (match == null) return NotFound();

            var msl = await _mslService.GetByMatchId(match.Id);
            var mslVM = _mapper.Map<List<MSLVM>>(msl);
            var matchVM = _mapper.Map<MatchVM>(match);
            var stadiumVM = _mapper.Map<StadiumVM>(match.Stadium);
            var detailInfo = new MatchInfo()
            {
                MSL = mslVM,
                Match = matchVM,
                Stadium = stadiumVM
            };

            return View(detailInfo);
        }     

        [HttpPost]
        public async Task<IEnumerable<MatchCalendarDataVM>> CalendarData(CalendarReturnDataVM calendarData)
        {
            if (!ModelState.IsValid)
            {
                return null;
            }

            try
            {
                DateTime start = DateTime.Parse(calendarData.Start);
                DateTime end = DateTime.Parse(calendarData.End);

                IEnumerable<Match> list;

                if (!calendarData.TeamId.HasValue)
                {
                    list = await _matchService.GetAll(start, end);
                } else
                {
                    list = await _matchService.GetByTeamId(start, end, calendarData.TeamId.Value);
                }

                List<MatchCalendarDataVM> listVM = _mapper.Map<List<MatchCalendarDataVM>>(list);
                return listVM;
            }
            catch (Exception e)
            {
                Debug.WriteLine("MatchesController: " + e.Message);
                return null;
            }

        }
    }
}

webproject1920/Controllers/ShopController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using webproject1920.Domain.Entities;
using webproject1920.Service.Interfaces;
using webproject1920.Util;
using webproject1920.Util.Mail;
using webproject1920.ViewModels;

namespace webproject1920.Controllers
{
    [Authorize]
    public class ShopController : Controller
    {
        private const string KEY_SHOPPINGCART = "ShoppingCart";

        private readonly IMapper _mapper;
        private readonly IMatchService _matchService;
        private readonly IMatchStadiumLocationService _mslService;
        private readonly ITeamsService _teamsService;
        private readonly ICompetitionsService _competitionsService;
        private readonly ILocationsService _locationsService;
        private readonly ITicketService _ticketService;
        private readonly IOrderLineService _orderLineService;
        private readonly IOrderService _orderService;
        private readonly ITeamCompetitionLocationService _tclService;
        private readonly ISubscriptionService _subscriptionService;
        private readonly IEmailSender _emailSender;

        public ShopController(IMapper mapper, IMatchService matchService, ITeamsService teamsService, IMatchStadiumLocationService mslService
            , ICompetitionsService competitionsService, ILocationsService locationsService, IOrderService orderService, IOrderLineService orderLineService,
            ITicketService ticketService, ITeamCompetitionLocationService tclService, ISubscriptionService subscriptionService, IEmailSender emailSender)
        {
            _mapper = mapper;
            _matchService = matchService;
            _teamsService = teamsService;
            _mslService = mslService;
            _competitionsService = competitionsService;
            _locationsService = locationsService;
            _orderLineService = orderLineService;
            _orderService = orderService;
            _ticketService = ticketService;
            _tclService = tclService;
            _subscriptionService = subscriptionService;
            _emailSender = emailSender;
        }

        public ActionResult Index()
        {
            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<ActionResult> Cart()
        {
            ShoppingCartVM cart;
            cart = HttpContext.Session.GetObject<ShoppingCartVM>(KEY_SHOPPINGCART);
            if (cart == null)
            {
                cart = new ShoppingCartVM
                {
                    Cart = new List<CartVM>()
                };
                HttpContext.Session.SetObject(KEY_SHOPPINGCART, cart);
            }

            if (TempData["CartError"] != null)
            {
                ModelState.AddModelError("Cart", TempData["CartError"].ToString());
                TempData["CartError"] = null;
            }

            cart.TotalPrice = 0.0;
            foreach (var item in cart.Cart)
            {
                if (item.MatchTicket.HasValue)
                {
                    var msl = await _mslService.GetById(item.MatchTicket.Value);

                    if (item.Count > msl.RemainingSeats)
                    {
                        item.Count = msl.RemainingSeats;
                        ModelState.AddModelError("Cart", "Niet genoeg beschikbare plaatsen voor 1 van de wedstrijden. Aantal werd aangepast.");
                    }
                    cart.TotalPrice += msl.Price * item.Count;
                }
                else if (item.TeamSubscription.HasValue) {
                    var tcl = await _tclService.GetById(item.TeamSubscription.Value);
                    cart.TotalPrice += tcl.Price;
                }
            }
            HttpContext.Session.SetObject(KEY_SHOPPINGCART, cart);
            
            return View(cart);
        }

        [HttpPost]
        public ActionResult Cart(CartVM vm)
        {
            ShoppingCartVM cart;
            cart = HttpContext.Session.GetObject<ShoppingCartVM>(KEY_SHOPPINGCART);
            if (cart == null)
            {
                cart = new ShoppingCartVM
                {
                    Cart = new List<CartVM>()
                };
                HttpContext.Session.SetObject(KEY_SHOPPINGCART, cart);
            }

            if (!ModelState.IsValid) RedirectToAction(nameof(Cart));

            if (vm.MatchTicket.HasValue && vm.ForMatchId.HasValue)
            {
                // Added match ticket
                if (vm.Count < 1)
                {
                    cart.Cart.RemoveAll(item => item.MatchTicket == vm.MatchTicket);
                }
                else if (cart.Cart.Any(x => x.MatchTicket == vm.MatchTicket))
                {
                    cart.Cart.Where(x => x.MatchTicket == vm.MatchTicket).ToList().ForEach(x => x.Count = vm.Count);
                }
                else
                {
                    cart.Cart.Add(vm);
                }

                int matchTicketCount = cart.Cart.Where(x => x.ForMatchId == vm.ForMatchId).Select(x => x.Count).Sum();
                if (matchTicketCount > 10)
                {
                    cart.Cart.Find(x => x.MatchTicket == vm.MatchTicket).Count = vm.Count - (matchTicketCount - 10);
                    TempData["CartError"] = "Maximum 10 tickets per match toegelaten!";
                }
            }
            else if (vm.TeamSubscription.HasValue && vm.ForTeamId.HasValue)
            {
                // Added subscription

                if (vm.Count < 1)
                {
                    cart.Cart.RemoveAll(item => item.TeamSubscription == vm.TeamSubscription);
                }
                else if (cart.Cart.Any(x => x.TeamSubscription == vm.TeamSubscription))
                {
                    cart.Cart.Where(x => x.TeamSubscription == vm.TeamSubscription).ToList().ForEach(x => x.Count = vm.Count);
                }
                else
                {
                    cart.Cart.Add(vm);
                }
            }
            HttpContext.Session.SetObject(KEY_SHOPPINGCART, cart);

            return RedirectToAction(nameof(Cart));
        }

        [HttpPost]
        public ActionResult RemoveCart(CartVM vm)
        {
            ShoppingCartVM cart = HttpContext.Session.GetObject<ShoppingCartVM>(KEY_SHOPPINGCART);
            if (cart == null) return NotFound();

            if (vm.MatchTicket.HasValue)
            {
                // Is ticket
                cart.Cart.RemoveAll(x => x.MatchTicket == vm.MatchTicket);
            }
            else if (vm.TeamSubscription.HasValue)
            {
                // Is subscription
                cart.Cart.RemoveAll(x => x.TeamSubscription == vm.TeamSubscription);
            }

            HttpContext.Session.SetObject(KEY_SHOPPINGCART, cart);

            return RedirectToAction(nameof(Cart));
        }

        [HttpPost]
        public ActionResult EmptyCart()
        {
            ShoppingCartVM cart = HttpContext.Session.GetObject<ShoppingCartVM>(KEY_SHOPPINGCART);
            if (cart == null) return NotFound();

            cart.Cart = new List<CartVM>();

            HttpContext.Session.SetObject(KEY_SHOPPINGCART, cart);

            return RedirectToAction(nameof(Cart));
        }

        [HttpGet]
        public async Task<IActionResult> Ticket(int matchId)
        {
            var match = await _matchService.GetById(matchId);
            if (match == null) return NotFound();

            if (DateTime.Now >= match.Start || DateTime.Now.AddMonths(1) < match.Start.Date) return NotFound();

            var msls = await _mslService.GetByMatchId(matchId);
            var mslsVM = _mapper.Map<List<MSLVM>>(msls);

            var matchVM = _mapper.Map<MatchVM>(match);
            var stadiumVM = _mapper.Map<StadiumVM>(match.Stadium);
            var shopInfo = new ShopTicketInfoVM()
            {
                MSLs = mslsVM,
                Match = matchVM,
                Stadium = stadiumVM
            };

            return View(shopInfo);
        }

        [HttpPost]
        public async Task<IActionResult> Ticket(int matchId, int mslId)
        {
            var match = await _matchService.GetById(matchId);
            if (match == null) return NotFound();
            var matchVM = _mapper.Map<MatchVM>(match);

            if (DateTime.Now >= match.Start || DateTime.Now.AddMonths(1) < match.Start.Date) return NotFound();

            var selectedMsl = await _mslService.GetById(mslId);
            var selectedMslVM = _mapper.Map<MSLVM>(selectedMsl);

            var msls = await _mslService.GetByMatchId(matchId);
            var mslsVM = _mapper.Map<List<MSLVM>>(msls);

            var stadiumVM = _mapper.Map<StadiumVM>(match.Stadium);
            var shopInfo = new ShopTicketInfoVM()
            {
                MSLs = mslsVM,
                SelectedMSL = selectedMslVM,
                Match = matchVM,
                Stadium = stadiumVM
            };

            return View(shopInfo);
        }

        [HttpGet]
        public async Task<IActionResult> Subscription(int teamId)
        {
            var team = await _teamsService.GetById(teamId);
            var competition = await _competitionsService.GetNextCompetition(DateTime.Now);
            var locations = await _locationsService.GetAll();

            var competitionVm = _mapper.Map<CompetitionVM>(competition);
            var locationVm = _mapper.Map<List<LocationVM>>(locations);

            var tcls = await _tclService.GetByTeamCompetitionId(team.Id, competition.Id);
            var tclVm = _mapper.Map<List<TCLVM>>(tcls);

            var teamVm = _mapper.Map<TeamVM>(team);

            var shopSubInfo = new ShopSubscriptionVM()
            {
                Team = teamVm,
                Tcl = tclVm,

webproject1920/Views/Matches/Calendar.cshtml
@model webproject1920.ViewModels.MatchCalendarVM
@{
    ViewData["Title"] = "Calendar";
}

<div class="jumbotron jumbotron-fluid jumbotronRemPadding jumbotron-rem-margin">
    <div class="calender-banner d-flex flex-column justify-content-center align-items-center px-1 py-5">
        <h1 class="text-white">Wedstrijden</h1>
        @if (Model.Team != null)
        {
            <h3 class="text-white">@Model.Team.Name</h3>
        }
    </div>
</div>

@section Links {
    <link rel="stylesheet" href="~/lib/fullcalendar/core/main.css" />
    @*<link rel="stylesheet" href="~/lib/fullcalendar/daygrid/main.css" />*@
    <link rel="stylesheet" href="~/lib/fullcalendar/list/main.css" />
}

<div id="matchcalendar">
</div>

@section Scripts {
    <script src="~/lib/fullcalendar/core/main.js"></script>
    <script src="~/lib/fullcalendar/list/main.js"></script>
    <script src='"~/lib/fullcalendar/core/locales-all.js'></script>
    <script>
        const teamId = '@Model.TeamId';
        document.addEventListener("DOMContentLoaded", function() {
        var calendarEl = document.getElementById("matchcalendar");

            var calendar = new FullCalendar.Calendar(calendarEl, {
            timeZone: 'UTC',
            plugins: ["list"],
            contentHeight: 'auto',
            defaultView: "listSeason",
             locale: 'nl',
            events: {
                url: "/Matches/CalendarData",
                method: "POST",
                extraParams: {
                    teamId
                }
            },
            views: {
                listSeason: {
                    type: 'list',
                    duration: { year: 1 },
                    buttonText: '3m'
                }
            },
            eventClick(info) {
                location.href = `/Matches/Details/${info.event.id}`;
                }
        });

            calendar.render();
        });
    </script>
}

webproject1920/Views/Matches/Details.cshtml
@model webproject1920.ViewModels.MatchInfo
@{
    ViewData["Title"] = "MatchDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron jumbo-match-detail">
    <div class="row m-0">
        <div class="col-md-5 h-100">
            <img src="@Model.Match.TeamHome.Logo" class="img-fluid mx-auto match-detail-logo d-block" />
            <p class="text-center font-weight-bold">@Model.Match.TeamHome.Name</p>
        </div>
        <div class="col-md-2 d-flex justify-content-center h-100 vertical-center">
            <i class="fas fa-times vs-icon "></i>
        </div>
        <div class="col-md-5 h-100">
            <img src="@Model.Match.TeamAway.Logo" class="img-fluid mx-auto match-detail-logo d-block" />
            <p class="text-center font-weight-bold">@Model.Match.TeamAway.Name</p>
        </div>
    </div>
</div>
<div class="text-center">
    <h1>@Model.Match.Stadium.Name</h1>
    <h4>Starting at @Model.Match.Start</h4>
    @if (DateTime.Now >= Model.Match.Start)
    {
        <p>Match afgelopen of gestart!</p>
    }
    else if (DateTime.Now.AddMonths(1) < Model.Match.Start.Date) {
        <p>Tickets beschikbaar 1 maand voor start!</p>
    }
    else
    {
        <a asp-controller="Shop" asp-action="Ticket" asp-route-matchId="@Model.Match.Id" class="btn btn-success">Koop een ticket voor deze match!</a>
    }
</div>

@section Scripts {
    <script>

    </script>
}